version: '3.4'
services:

  minios3test:
    image: minios3test
    build:
      context: "."
      dockerfile: ModelsApp.S3/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: '8080'
    ports:
    - 8080:8080
    links:
    - "minio:minio"
    depends_on:
    - minio
    networks:
    - minionetwork

  minio:
    image: quay.io/minio/minio
    ports:
    - 9000:9000
    - 9001:9001
    networks:
      minionetwork:
        aliases: 
        - minio
    volumes:
    - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: '1234567890'
      MINIO_DEFAULT_BUCKETS: testbucket
    restart: always
    command: server /data --console-address :9001


networks:
  minionetwork:
    ipam:
        driver: default
        config:
        - gateway: 172.24.0.1
          subnet: 172.24.0.0/24
    driver: bridge
  

volumes:
  minio_data: 
